### ISSUE TITLE
Busting Cached Markdown

### ISSUE THREAD

**Issue by BryanSchuetz** [daviddarnes/netlify-plugin-ghost-markdown#29]
I noticed that updating tags on a post in Ghost (not sure if this applies to all metadata, but probably) won't invalidate the cache when netlify builds. Hope that makes sense. Basically, if I go to Ghost and update the tags on a post, which triggers a Netlify Build—the Netlify won't replaced the cached markdown, with what should be new markdown coming from ghost with the updated tags.

At least that seems to be how it's working when running netlify build locally. If I change text in the body of the post—things work as I'd expect.

**Comment by daviddarnes** [comment]
Are you removing / adding tags to a post? Because that's technically what a post update should be. The cache is busted when there's a new `updated_at` value so I'm surprised this doesn't qualify. We may need to investigate this up the chain and ask someone at Ghost for why this is the case

**Comment by daviddarnes** [comment]
Going to close this issue and will reopen it if it's still a problem. I'm hoping that Ghost fixed this at their end
