### ISSUE TITLE
`item.html.split()` sometimes fails

### ISSUE THREAD

**Issue by ehmicky** [daviddarnes/netlify-plugin-ghost-markdown#4]
It seems that the [following line of code](https://github.com/daviddarnes/netlify-plugin-ghost-markdown/blob/926893a9a4837a322e0f159fb0f369b8bc689d68/index.js#L102) sometimes fails:

```js
...item.html.split('"').filter(slice => slice.includes(ghostImagePath)),
```

With `Cannot read property 'split' of null`, i.e. `item.html` is sometimes `null`.

**Comment by daviddarnes** [comment]
Interesting, I wonder if it's from pages with no content at all, and the html is returned as `null`?

**Comment by ehmicky** [comment]
I am not sure, but this error seems to happen several times per day.

**Comment by daviddarnes** [comment]
Per day? I had no idea this plugin was being used so frequently. I could really do with some more time to bring this all up to date. My current to dos are:
- Finish updating the plugin to the latest Build Plugins spec
- Update my article to match this new spec, and prevent sharing outdated code
- Attempt to provide a decent working example. Currently struggling to run a demo within the repo due "it's meta" issues. See: https://community.netlify.com/t/creating-demos-for-build-plugins/12774

**Comment by ehmicky** [comment]
There's no rush! Sorry to make it sound otherwise :)
