### ISSUE TITLE
`posts is not iterable` error

### ISSUE THREAD

**Issue by ehmicky** [daviddarnes/netlify-plugin-ghost-markdown#5]
A build is getting the following error:

```
posts is not iterable 
    /opt/build/repo/node_modules/netlify-plugin-ghost-markdown/index.js:100:9 onPreBuild
    internal/process/next_tick.js:68:7 process._tickCallback
```

It seems this would indicate that `ghostContentApi.posts()` return value is not always an array.

**Comment by daviddarnes** [comment]
I think that might have just been me using the plugin wrong. Thanks thought 😅

**Comment by daviddarnes** [comment]
@ehmicky thanks for the error reports! Keep an eye out as I just published a new version with my and your updates. I had to remove the `default` items in the manifest as they were erroring when I used `netlify build`

**Comment by ehmicky** [comment]
Thanks for fixing it! I actually saw it and marked those errors as solved :)
I will be notified if it was to be triggered again (but I think it won't) and will forward it.

For the `netlify build` error: this might be due to the `@netlify/cli` version you are using. The latest version might solve this problem.

**Comment by daviddarnes** [comment]
I updated the CLI before starting this stuff so not sure why it was happening :/
